---

- name: install firewalld
  package:
    name: firewalld
    state: present

- name: install python3-firewall
  package:
    name: python3-firewall
    state: present

- name: start service firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: started
    daemon_reexec: yes

- name: open port in firewall
  firewalld:
    port: "{{ nginx_port }}/tcp"
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
  notify:
    - restart firewalld
