---
# Inspired by https://jupyterhub.readthedocs.io/en/stable/installation-guide-hard.html

- name: create citc-app-jh user
  user:
    name: citc-app-jh
    create_home: no
    system: yes
  register: user

- include_tasks: firewall.yml

- name: install npm
  package:
    name: npm
    state: present

- name: Install configurable-http-proxy
  npm:
    name: configurable-http-proxy
    global: yes

- name: install Python 3
  package:
    name:
      - python38
      - python38-pip
    state: present

- name: create virtualenv
  pip:
    name:
      - jupyterhub
      - notebook
      - sudospawner
      - jupyterlab
    virtualenv: /opt/jupyterhub_venv
    virtualenv_command: /bin/python3 -m venv
  register: jupyterhub_venv

- name: ensure /var/run/citc exists
  file:
    path: /var/run/citc
    state: directory
  register: citc_run_dir

- name: ensure jupyterhub run dir exists
  file:
    path: "{{ citc_run_dir.path }}/jupyterhub"
    state: directory
    owner: "{{ user.name }}"
  register: jupyterhub_run_dir

- name: create the JupyterLab config dir
  file:
    path: "{{ jupyterhub_venv.virtualenv }}/etc/jupyterhub/"
    state: directory
    owner: "{{ user.name }}"
  register: jupyterhub_config_dir

- name: Set JupyterHub config
  template:
    src: jupyterhub_config.py.j2
    dest: "{{ jupyterhub_config_dir.path }}/jupyterhub_config.py"
  register: jupyterhub_config_file
  notify: restart jupyterhub

- name: Install JupyterHub service file
  template:
    src: jupyterhub.service.j2
    dest: /etc/systemd/system/jupyterhub.service
  notify: restart jupyterhub

- name: start and enable jupyterhub
  systemd:
    name: jupyterhub
    state: started
    enabled: yes
    daemon_reexec: yes

- name: ensure that sudospawner is executable
  file:
    path: "{{ jupyterhub_venv.virtualenv }}/bin/sudospawner"
    mode: a+x

- name: Add sudospawner for sudoers
  copy:
    content: |
      Runas_Alias JUPYTER_USERS = rhea, %users
      Cmnd_Alias JUPYTER_CMD = {{ jupyterhub_venv.virtualenv }}/bin/sudospawner
      {{ user.name }} ALL=(JUPYTER_USERS) NOPASSWD:JUPYTER_CMD
    dest: /etc/sudoers.d/95-citc-app-jupyterhub-sudospawner
    validate: /usr/sbin/visudo -cf %s

- include_tasks: pam.yml
  when: jupyterhub_pam_shadow

- include_tasks: nginx.yml
