---

# Based on https://jupyterhub.readthedocs.io/en/stable/reference/config-proxy.html

- name: install nginx
  include_role:
    name: nginxinc.nginx
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: citc-app-jupyterhub.conf
        conf_file_location: /etc/nginx/conf.d/
        servers:
          server1:
            listen:
              listen_localhost:
                port: "{{ nginx_port }}"
            server_name: localhost
            access_log:
              - name: main
                location: /var/log/nginx/jupyterhub_access.log
            error_log:
              location: /var/log/nginx/jupyterhub_error.log
              level: warn
            reverse_proxy:
              locations:
                default:
                  location: /
                  proxy_pass: "http://127.0.0.1:{{ proxy_port }}"
                  proxy_set_header:
                    header_host:
                      name: Host
                      value: $host:$server_port
                    header_x_real_ip:
                      name: X-Real-IP
                      value: $remote_addr
                    header_x_forwarded_for:
                      name: X-Forwarded-For
                      value: $proxy_add_x_forwarded_for
                  websocket: true
