---

- name: Verify
  hosts: all
  tasks:
  - name: Check that JupyterHub proxy is running
    uri:
      url: "http://localhost:{{ proxy_port }}"
  - name: Check that nginx is running
    uri:
      url: "http://localhost:{{ nginx_port }}"
  - name: add test user
    user:
      name: testuser
      password: "{{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}"
      group: users
  - name: Check that sudoers works
    command: sudo -n -u testuser /opt/jupyterhub_venv/bin/sudospawner --help  # noqa 301
    become: yes
    become_user: citc-app-jh
  - name: Check that sudoers fails command correctly
    command: sudo -n -u testuser echo 'fail'  # noqa 301
    become: yes
    become_user: citc-app-jh
    register: sudoers_test_fail
    failed_when: sudoers_test_fail.rc == 0
  - name: Login to JupyterHub as testuser
    uri:
      url: "http://localhost:{{ nginx_port }}/hub/login?next="
      method: POST
      body_format: form-urlencoded
      body:
        username: testuser
        password: mypassword
      status_code: 302
    register: login
