name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install Poetry
        run: pip install poetry
      - name: Setup package
        run: poetry install
      - name: Run molecule test
        run: |
          cd roles/jupyterhub
          poetry run molecule test
